<?php
/**
 * Created by PhpStorm.
 * User: andrey
 * Date: 07.02.18
 * Time: 14:14
 */

namespace app\controllers;

use yii\web\Controller;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\SignupForm;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;

class AppController extends Controller {
    protected function setMeta($title = null, $keywords = null, $description = null) {
        $this->view->title = $title;
        $this->view->registerMetaTag(['name' => 'keywords', 'content' => "$keywords"]);
        $this->view->registerMetaTag(['name' => 'description', 'content' => "$description"]);
    }

//    public function behaviors() {
//        return parent::behaviors(); // TODO: Change the autogenerated stub
//    }

//    public function actionSignup()
//    {
//        $model = new SignupForm();
//
//        if ($model->load(Yii::$app->request->post())) {
//            if ($user = $model->signup()) {
//                if (Yii::$app->getUser()->login($user)) {
//                    return $this->goHome();
//                }
//            }
//        }
//        return $this->render('signup', [
//            'model' => $model,
//        ]);
//    }

}